name: prayer_app
description: "مواقيت الصلاة — المصدر الرسمي: وزارة الأوقاف والشؤون الإسلامية"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  html: ^0.15.4
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  workmanager: ^0.5.2
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
